MeterLab/MeterLab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from .views import dashboard

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")),
    path('', dashboard),
    path('home/', include('Users.urls')),
    path('meters/', include('Meters.urls')),
    path('signatory/', include('Signatory.urls')),
]

MeterLab/Users/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from MeterLab .views import dashboard as home

from .views import *

urlpatterns = [
    # path('', LoginView.as_view(), name='login'),
    path('', login, name='login'),
    path('home', home, name='home'),
    path('regs', register, name='register'),
    path('logout', logout_view, name='logout'),

    # path('admin/', admin.site.urls),
]

MeterLab/Meters/models.py
import datetime
from decimal import Decimal
from django.db import models
from datetime import date
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class meters(models.Model):
    id = models.AutoField(primary_key=True)
    dateforwarded = models.DateField(("Date"), default=date.today)
    rrnumber = models.CharField(max_length=145, db_index=True)
    brand = models.CharField(max_length=145)
    metertype = models.CharField(max_length=145, null=True)
    serialnos = models.CharField(max_length=145, null=True)
    units = models.IntegerField(default=0)              # meter count
    active = models.PositiveSmallIntegerField(
        default=0, null=False)        # active, deleted

    userid = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "meters"

class meterserials(models.Model):
    id = models.AutoField(primary_key=True)
    idmeters = models.ForeignKey(
        meters, db_column='idmeters', related_name="meters", on_delete=models.CASCADE)
    serialno = models.CharField(max_length=45, null=False)
    ampheres = models.CharField(max_length=45, null=True)
    accuracy = models.CharField(max_length=45, null=True)
    wms_status = models.PositiveSmallIntegerField(
        default=0, null=True)    # 0=forwarded, 1=pending, 2=returned
    status  = models.PositiveSmallIntegerField(
        default=0, null=True)    # pending, passed, failed
    active = models.PositiveSmallIntegerField(
        default=0, null=True)        # active, deleted

    userid = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "meter_serials"

class meterserials_details(models.Model):
    id = models.AutoField(primary_key=True)
    idmeterserials = models.ForeignKey(meters, db_column='idmeterserials', related_name="meter_serials", on_delete=models.CASCADE)
    testdate = models.DateField(("Date"), default=date.today)
    gen_average = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    fullload_average = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    fl1 = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    fl2 = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    fl3 = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    lightload_average = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    ll1 = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    ll2 = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    ll3 = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])

    reading = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(Decimal('0.00'))])
    type = models.PositiveSmallIntegerField(default=0, null=True)        # type, class
    volts = models.CharField(max_length=45)
    phase = models.CharField(max_length=45)
    kh = models.CharField(max_length=45)
    ta = models.CharField(max_length=45)
    remarks = models.CharField(max_length=245)

    active = models.PositiveSmallIntegerField(default=0, null=True)        # active, deleted
    isdamage = models.BooleanField(default=False)
    userid = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "meter_serials_details"
        # abstract = True

MeterLab/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meter Calibration</title>
    <link rel="icon" href="{% static "dist/img/zaneco1x1.png" %}">

    <!-- Google Font: Source Sans Pro -->
    <!-- Ionicons -->
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{% static "plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static "plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{% static "plugins/jqvmap/jqvmap.min.css" %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static "dist/css/adminlte.min.css" %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static "plugins/overlayScrollbars/css/OverlayScrollbars.min.css" %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static "plugins/daterangepicker/daterangepicker.css" %}">
    <!-- summernote -->
    <link rel="stylesheet" href="{% static "plugins/summernote/summernote-bs4.min.css" %}">
    <!-- end index.html -->

    <link rel="stylesheet" href="{% static "plugins/fontawesome-pro-5.13.0-web/css/all.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/datatables-responsive/css/responsive.bootstrap4.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/datatables-select/css/select.bootstrap4.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/datatables-buttons/css/buttons.bootstrap4.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/select2/css/select2.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css" %}">

    <!-- <link rel="stylesheet" href="{% static "plugins/optionedit/jquery-editable-select.css" %}" type="text/css"> -->
    <link rel="stylesheet" href="{% static "plugins/optionedit/jquery-editable-select.min.css" %}" type="text/css">

    <link rel="stylesheet" type="text/css" href={% static "dist/css/selectdatatables/jquery.dataTables.min.css" %}">
    <link rel="stylesheet" type="text/css" href={% static "dist/css/selectdatatables/select.dataTables.min.css" %}">
    <!-- <link rel="stylesheet" type="text/css" href={% static "dist/css/selectdatatables/buttons.dataTables.min.css" %}"> -->
    <!-- <link rel="stylesheet" type="text/css" href={% static "dist/css/selectdatatables/editor.dataTables.min.css" %}">
    <link rel="stylesheet" type="text/css" href={% static "dist/css/selectdatatables/datatables.min.css" %}"> -->

    <link rel="stylesheet" href="{% static "plugins/toastr/toastr.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/toast/toast.min.css" %}">

</head>

<!-- <nav class="main-header navbar navbar-expand navbar-dark navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
</nav> -->
{% if request.user.is_authenticated %}
    {% block header %}
    {% endblock header %}

    <!-- <body class="sidebar-mini sidebar-collapse text-sm" style="height: auto;"> -->
    <body class="sidebar-mini text-sm" style="height: auto;"></body>
        <div class="wrapper">
            {% include 'base/sidebar.html' %}
            {% block content %}
            {% endblock content %}
        </div>

    </body>
{% else %}
    {% include 'base/login.html' %}
{% endif %}




<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<script src="{% static "plugins/jquery-ui/jquery-ui.min.js" %}"></script>
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<script src="{% static "plugins/chart.js/Chart.min.js" %}"></script>
<script src="{% static "plugins/sparklines/sparkline.js" %}"></script>
<script src="{% static "plugins/jqvmap/jquery.vmap.min.js" %}"></script>
<script src="{% static "plugins/jqvmap/maps/jquery.vmap.usa.js" %}"></script>
<script src="{% static "plugins/jquery-knob/jquery.knob.min.js" %}"></script>
<script src="{% static "plugins/moment/moment.min.js" %}"></script>
<script src="{% static "plugins/daterangepicker/daterangepicker.js" %}"></script>
<script src="{% static "plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<script src="{% static "plugins/summernote/summernote-bs4.min.js" %}"></script>
<script src="{% static "plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js" %}"></script>

<script src="{% static "plugins/datatables/jquery.dataTables.min.js" %}"></script>
<script src="{% static "plugins/datatables-bs4/js/dataTables.bootstrap4.min.js" %}"></script>
<script src="{% static "plugins/datatables-responsive/js/dataTables.responsive.min.js" %}"></script>
<script src="{% static "plugins/datatables-responsive/js/responsive.bootstrap4.min.js" %}"></script>

<script src="{% static "plugins/datatables-select/js/dataTables.select.min.js" %}"></script>
<script src="{% static "plugins/datatables-select/js/select.bootstrap4.min.js" %}"></script>

<script src="{% static "plugins/datatables-buttons/js/buttons.bootstrap4.min.js" %}"></script>
<script src="{% static "plugins/datatables-buttons/js/dataTables.buttons.min.js" %}"></script>
<script src="{% static "plugins/datatables-buttons/js/dataTables.html5.min.js" %}"></script>
<script src="{% static "plugins/datatables-buttons/js/dataTables.print.min.js" %}"></script>
<script src="{% static "plugins/datatables-buttons/js/dataTables.colVis.min.js" %}"></script>

<!-- <script src="{% static "plugins/datatables-buttons/js/buttons.flash.min.js" %}"></script> -->
<!-- Toastr -->
<script src="{% static "plugins/toastr/toastr.min.js" %}"></script>
<script src="{% static "plugins/toast/toast.min.js" %}"></script>

<script src="{% static "plugins/select2/js/select2.full.min.js" %}"></script>

<!-- <script src="{% static "plugins/optionedit/jquery-editable-select.js" %}"></script> -->
<!-- <script src="{% static "plugins/optionedit/jquery-editable-select.min.js" %}"></script> -->

<script src="{% static "dist/js/adminlte.js" %}"></script>
<script src="{% static "dist/js/demo.js" %}"></script>
<script src="{% static "dist/js/pages/dashboard.js" %}"></script>

<!-- <script type="text/javascript" src="{% static "dist/css/selectdatatables/jquery.dataTables.min.js" %}"></script> -->
<!-- <script type="text/javascript" src="{% static "dist/css/selectdatatables/dataTables.select.min.js" %}"></script> -->
<!-- <script type="text/javascript" src="{% static "dist/css/selectdatatables/dataTables.buttons.min.js" %}"></script> -->
<!-- <script type="text/javascript" src="{% static "dist/css/selectdatatables/dataTables.editor.min.js" %}"></script>
<script type="text/javascript" src="{% static "dist/css/selectdatatables/tabledit.min.js" %}"></script>
<script type="text/javascript" src="{% static "dist/css/selectdatatables/dataTables.keyTable.min.js" %}"></script> -->

</html>


<script>

    $('.select2').select2();
    var rrnumber = '';

    $(document).ready(function () {

        let table_rr = $('#table_rr').DataTable({
            "searching": true,
            "processing": true,
            "stateSave": true,
            "info": true,
            "paging": true,
            "lengthChange": true,
            "autoWidth": false,
            "responsive": true,
            "columnDefs": [{
                "targets": [ 6 ],
                "className": "text-right",
            }],
            "keys": true,
            "keys": { "blurable": false },
            "select": true,
            "select": {
                "style": "os",
            },
            "serverSide": true,
            "processing": true,
            "ajax": function (data, callback, settings) {
                var sort_column_name = data.columns[data.order[0].column].data.replace(/\./g, "__");
                var direction = "";
                if (data.order[0].dir == "desc") { direction = "-" };
                $.get("{% url 'rrviews' %}", {
                    limit: data.length,
                    start: data.start,
                    filter: data.search.value,
                    order_by: direction + sort_column_name
                }, function (res) {
                    callback({
                        recordsTotal: res.length,
                        recordsFiltered: res.length,
                        data: res.objects
                    });
                });
            },
            columns: [
                { "data": "id" },
                { "data": "dateforwarded" },
                { "data": "rrnumber", "render": function (data, type, row) {
                        return '<td style="width: fit-content;"> <a href="seriallist/'+ row["id"] +'">' + data + '</a></td>'
                    }
                },
                { "data": "brand" },
                { "data": "serialnos" },
                { "data": "metertype" },
                { "data": "units" },
                { "data": "id", "render": function (data, type, row) {
                    if ('{{ request.user.is_superuser }}' == 'True') {
                    return '<center><a href="#" class="btn btn-danger btn-xs text-sm" title="Delete" onclick = "delete_meters(' + row["id"] + ')" ><i class="fal fa-trash-alt"></i><span style="font-size: 12px;"> Delete</span></a></center>'
                    } else {
                    return '<center><a href="#" class="btn btn-default btn-xs text-sm" title="Delete"><i class="fal fa-trash-alt"></i><span style="font-size: 12px;"> Delete</span></a></center>'
                    }
                    }
                },
            ]
        });
        table_rr.column(0).visible(false);
    });

    let opt_supplier = '{{ opt_supplier }}';
    let opt_rr = '{{ opt_rr }}';
    if (opt_supplier != '') $("#id_supplier").select2().val(opt_supplier).trigger('change.select2');
    if (opt_rr != '') $("#id_rrnumber").select2().val(opt_rr).trigger('change.select2');

    function meter_serial(params) {
        $('#add-serials').modal('show').draggable({ handle: ".modal-header" });
    }

    function msgalert(header, remarks, ico) {
        if (ico == 1) icon = 'fal fa-save fa-lg';
        if (ico == 2) icon = 'fas fa-pencil-alt fa-lg';
        if (ico == 3) icon = 'fal fa-trash-alt fa-lg';
        $(document).Toasts('create', {
            class: 'bg-white',
            title: '<span style="font-size: 12px;"> ' + header + ' </span>',
            subtitle: '<a href="" class="nav-link" id="">reserved!</a>',
            position: 'bottomRight',
            icon: icon,
            body: '<div class="col-md-9 row" style="width: 300px"><span style="font-size:13px;">' + remarks + '</span></div>',
            autohide: true,
            delay: 10000,
        });
};
</script>

MeterLab/templates/base/header.html
{% load static %}
{% block header %}
<nav class="main-header navbar navbar-expand navbar-dark navbar-gray-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <!-- <ol class="breadcrumb float-sm-right hidden clearfix">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            {% if header is not null %}
            <li class="breadcrumb-item active"><a href="#" class="nav-link">{{ header|title }}</a></li>
            {% endif %}
        </ol> -->

        <!-- <li class="nav-item clearfix"> -->
            <li><a href="/" class="nav-link">Dashboard</a></li>
            {% if header is not null %}
            <li><span class="nav-link">/</span></li>
            <li><a href="#" class="nav-link">{{ header|capfirst }}</a></li>
            {% endif %}
        <!-- </li> -->

    </ul>

    <!-- SEARCH FORM
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form> -->


    <ul class="navbar-nav ml-auto">
        <li class="nav-item clearfix">
        {% if request.user.is_authenticated %}
        <!-- <li><a href="#" class="nav-link" style="text-transform:uppercase">{{ username }}</a></li>
        <li><a href="{% url 'logout' %}" class="nav-link">Logout</a></li> -->
        {% else %}
        <li><a href="#" class="nav-link">Register</a></li>
        <li><a href="{% url 'login' %}" class="nav-link">Login</a></li>
        {% endif %}
        </li>

        <!-- <li class="nav-item clearfix">
        <li class="nav-item dropdown">
            <a class="nav-link" href="#" data-toggle="dropdown" title="Request Materials">
                <i class="fal fa-comment-alt-exclamation"></i>
                <p class="badge badge-success navbar-badge"
                    style="font-size: 8px; font-weight: bold; margin-top:-6px; display: inline-block">

                </p>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">Request Materials</span>
                <div class="dropdown-divider"></div>

                <div id="request">
                </div>
                <a href="#" class="dropdown-item dropdown-footer"></a>
            </div>

        </li>
        </li> -->

        <!-- <li class="nav-item clearfix">
        <li class="nav-item dropdown">

            <a class="nav-link" href="#" data-toggle="dropdown">
                <i class="far fa-bell"></i>
                <p class="badge badge-warning navbar-badge"
                    style="font-size: 8px; font-weight: bold; margin-top:-6px; display: inline-block">
                </p>
            </a>

            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="reorderitems.php" class="dropdown-item">
                    <i class="fal fa-exclamation mr-2"></i> Reorder Items
                    <span class="float-right text-muted text-sm">
                    </span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">

                    <i class="fal fa-exclamation mr-2"></i> Returned to Supplier
                    <span class="float-right text-muted text-sm">
                    </span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fad fa-alarm-snooze mr-2"></i> reserved...
                    <span class="float-right text-muted text-sm">0</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer"></a>
            </div>
        </li>
        </li> -->
        {% if request.user.is_authenticated %}
        <li class="nav-item clearfix" style="border-right: 10px;">
            <div class="user-panel d-flex">
                <div class="image">
                    <img src="{% static 'dist/img/user1-128x128.jpg' %}" class="img-circle img-bordered-sm">
                </div>
            </div>
        <li class="nav-item dropdown">
            <a class="nav-link" href="#" data-toggle="dropdown">
                <p data-toggle="tooltip" title="Logout" href="#">{{ request.user.username|title }}
                <i class="fa fa-caret-down fa-fw"></i>
                </p>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <div class="card-body box-profile">
                    <div class="text-center">
                        <a data-toggle="modal" href="#change_user_picture">
                            <img class="profile-user-img img-fluid img-circle img-bordered-sm" src="{% static 'dist/img/user1-128x128.jpg' %}"
                                alt="User profile picture">
                        </a>
                    </div>
                    <!-- <span class="profile-username text-center"></span> -->
                    <p class="text-muted text-center">{{ request.user.email }}</p>
                </div>

                <div class="dropdown-divider"></div>
                <a href="{% url 'logout' %}" class="dropdown-item dropdown-footer" style="font-size: 12px;"><i
                        class="fal fa-sign-out-alt mr-1"></i>Logout</a>
            </div>
        </li>
        </li>
        {% endif %}

    </ul>
</nav>

<!-- <script type="text/javascript">
    function download_tools() {
        // var ok = confirm('Are you sure to download this reporting tools?');
        // if (ok == true) {
        //     var redirectWindow = window.open('http://192.168.1.2/zanecowms/admin/download/WMSReportTools.rar');
        //     redirectWindow.location;
        // }
    }

</script> -->

{% endblock header %}

MeterLab/templates/base/index.html
{% load static %}

{% block header %}
{% include 'base/header.html' %}
{% endblock header %}

{% block content %}

  <div class="content-wrapper">
    <div class="content-header">
      <!-- <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Dashboard</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div>
        </div>
      </div> -->
    </div>

    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
                <h3>150</h3>

                <p>New Orders</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>53<sup style="font-size: 20px">%</sup></h3>

                <p>Bounce Rate</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
              <div class="inner">
                <h3>44</h3>

                <p>User Registrations</p>
              </div>
              <div class="icon">
                <i class="ion ion-person-add"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
              <div class="inner">
                <h3>65</h3>

                <p>Unique Visitors</p>
              </div>
              <div class="icon">
                <i class="ion ion-pie-graph"></i>
              </div>
              <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
        </div>
        <div class="row">
        </div>
      </div>
    </section>
  </div>
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2020 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  {% endblock content %}

MeterLab/templates/base/sidebar.html
{% load static %}
<!-- <aside class="main-sidebar sidebar-dark-primary elevation-1"> -->
<aside class="main-sidebar sidebar-dark-primary elevation-2 " style="position: fixed;">
    <a href="{% url 'home' %}" onclick="" class="brand-link bg-info">
        <img src="{% static "dist/img/zaneco3x3.png" %}" alt="ZANECO Logo" class="brand-image-xl img-circle"
            style="opacity: .8">
        <span class="brand-text font-weight-heavy"><span style="font-size: 24px;">ZANECO</span> MeterLab</span>
    </a>
    <!-- <div class="sidebar-header">
        <h1>Navigation</h1>
    </div> -->
    <div class="sidebar">
        <nav class="mt-2">
            <!-- <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent nav-flat " data-widget="treeview" role="menu" data-accordion="false" data-api="treeview" > -->
            <ul class="nav nav-pills nav-sidebar flex-column nav-flat " data-widget="treeview" role="menu" data-accordion="false"   >
                <li class="nav-item has-treeview menu-open" id="sb_otherinfo">
                    <!-- <a href="#" class="nav-link" id="sb_otherinfo_b">
                        <i class="nav-icon fas fa-book-spells"></i>
                        <p>Sources<i class="right fas fa-angle-left"></i></p>
                    </a> -->
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/" class="nav-link" id="sb_itemindex"><i class="nav-icon far fa-chart-network"></i>
                                <p>Dashboard</p>
                            </a>
                        </li>
                    </ul>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/meters" class="nav-link" id="sb_itemindex"><i class="nav-icon fal fa-tachometer-alt-slow"></i>
                                <p>Meters</p>
                            </a>
                        </li>
                    </ul>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="/signatory" class="nav-link" id="sb_itemindex"><i class="nav-icon fal fa-signature"></i>
                                <p>Signatory</p>
                            </a>
                        </li>
                    </ul>

                </li>

                <!-- <li class="nav-item has-treeview menu-open" id="sb_materials">
                    <a href="#" class="nav-link" id="sb_materials_b">
                        <i class="nav-icon fas fa-tools"></i>
                        <p>Materials<i class="right fas fa-angle-left"></i></p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="" class="nav-link" id="sb_issuance"><i class="nav-icon fal fa-hands-helping"></i>
                                <p>
                                    Reserved
                                    <span class="right badge badge-warning"></span>
                                </p>
                            </a>
                        </li>
                    </ul>
                </li> -->

            </ul>
        </nav>
    </div>
</aside>


<script>
    // $(document).ready(function () {
    //     $('#ulExpCol_1').collapse('toggle');
    // });
</script>